/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Menu;

import com.formdev.flatlaf.FlatLightLaf;

import BUS.BUS_Questions;
import DTO.DTO_Questions;

//import static com.microsoft.schemas.office.excel.STObjectType.Enum.table;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import GUI.CRUD.SuaCauHoi;
// import themcauhoir
import GUI.CRUD.ThemCauHoi;

/**
 *
 * @author kiet
 */
public final class QuanLyCauHoi extends javax.swing.JPanel {
        GUI.GUI_MainFrm main;

        // Add these variables at the class level
        private javax.swing.JComboBox<String> cboTopic;
        private javax.swing.JComboBox<String> cboDifficulty;
        private ArrayList<DTO.DTO_Topic> topics;

        public QuanLyCauHoi(GUI.GUI_MainFrm main) {
                this.main = main;
                initComponents();
                loadTopics(); // Load topics for the combo box
                loadQuestionsTable();
        }

        private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {

                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow >= 0) {
                        int questionId = (Integer) jTable1.getModel().getValueAt(selectedRow, 0);
                        GUI.CRUD.XemChiTietCauHoi xemChiTietDlg = new GUI.CRUD.XemChiTietCauHoi(
                                        (java.awt.Frame) SwingUtilities.getWindowAncestor(this), true, questionId);
                        xemChiTietDlg.setVisible(true);
                } else {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Vui lòng chọn một câu hỏi để xem chi tiết!",
                                        "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel2 = new javax.swing.JPanel();
                txtSearch = new com.raven.suportSwing.TextField();
                myButton2 = new com.raven.suportSwing.MyButton();
                lblSearch = new javax.swing.JLabel();
                jPanel7 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                scrollBarCustom1 = new com.raven.suportSwing.ScrollBarCustom();

                setBackground(new java.awt.Color(255, 255, 255));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                txtSearch.setLabelText("Tìm theo tên or mã");
                txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                txtSearchFocusGained(evt);
                        }
                });
                txtSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtSearchActionPerformed(evt);
                        }
                });
                txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtSearchKeyReleased(evt);
                        }
                });

                myButton2.setBackground(new java.awt.Color(204, 255, 255));
                myButton2.setText("Reset");
                myButton2.setBorderColor(new java.awt.Color(153, 255, 255));
                myButton2.setRadius(20);
                myButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                myButton2ActionPerformed(evt);
                        }
                });

                lblSearch.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
                lblSearch.setForeground(new java.awt.Color(255, 51, 0));

                jPanel7.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-75.png"))); // NOI18N
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel2MousePressed(evt);
                        }
                });

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-85.png"))); // NOI18N
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel4MousePressed(evt);
                        }
                });

                jLabel3.setText("Thêm");

                jLabel5.setText("Sửa");

                jLabel6.setText("Xóa");

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-view-75.png"))); // NOI18N

                jLabel8.setText("Xem chi tiết");

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-edit-75.png"))); // NOI18N
                jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel1MousePressed(evt);
                        }
                });
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel7MousePressed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel2))
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(28, 28, 28)
                                                                                                .addComponent(jLabel3)))
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                67,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jLabel4))
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(41, 41, 41)
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(69, 69, 69)
                                                                                                .addComponent(jLabel6)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel7)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(jLabel8)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel7Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(16, 16, 16)
                                                                                                                                .addComponent(jLabel7,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                57,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addContainerGap()
                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(jPanel7Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                false)
                                                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                0,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)))))
                                                                                                .addGap(19, 19, 19))
                                                                                .addGroup(jPanel7Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(jPanel7Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(jPanel7Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel5,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel6,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel8)))
                                                                .addContainerGap(12, Short.MAX_VALUE)));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null }
                                },
                                new String[] {
                                                "Mã sản phẩm", "Tên sản phẩm", "Bộ xử lý", "Hệ điều hành",
                                                "Thương hiệu", "Thời gian bảo hành"
                                }));
                jScrollPane1.setViewportView(jTable1);

                // Add topic combobox with label
                JLabel lblTopic = new javax.swing.JLabel("Chủ đề:");
                lblTopic.setFont(new java.awt.Font("Segoe UI", 0, 14));
                cboTopic = new javax.swing.JComboBox<>();
                cboTopic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả chủ đề" }));
                cboTopic.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                filterQuestions();
                        }
                });

                // Add difficulty combobox with label
                JLabel lblDifficulty = new javax.swing.JLabel("Độ khó:");
                lblDifficulty.setFont(new java.awt.Font("Segoe UI", 0, 14));
                cboDifficulty = new javax.swing.JComboBox<>();
                cboDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dễ", "Vừa", "Khó" }));
                cboDifficulty.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                filterQuestions();
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(txtSearch,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                220,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(lblTopic)
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(cboTopic,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                150,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(lblDifficulty)
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(cboDifficulty,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                100,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(myButton2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(147, 147, 147))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(215, 215, 215)
                                                                                                .addComponent(lblSearch,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                308,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                                                                                                238,
                                                                                                                Short.MAX_VALUE)))
                                                                .addComponent(jPanel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(363, 363, 363))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1)
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.CENTER)
                                                                                                                .addComponent(txtSearch,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(lblTopic)
                                                                                                                .addComponent(cboTopic,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(lblDifficulty)
                                                                                                                .addComponent(cboDifficulty,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(myButton2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(lblSearch,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                14,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                607,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(120, Short.MAX_VALUE)));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap(1714, Short.MAX_VALUE)
                                                                .addComponent(scrollBarCustom1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(39, 39, 39)
                                                                .addComponent(scrollBarCustom1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 5,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_myButton2ActionPerformed
                // Reset the search field and reload all questions
                txtSearch.setText("");
                lblSearch.setText("");
                cboTopic.setSelectedIndex(0); // Reset topic to "All topics"
                cboDifficulty.setSelectedIndex(0); // Reset difficulty to "All"
                loadQuestionsTable();
        }// GEN-LAST:event_myButton2ActionPerformed

        private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtSearchKeyReleased
                // Search for questions matching the keyword
                filterQuestions();
        }// GEN-LAST:event_txtSearchKeyReleased

        private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtSearchFocusGained

        }// GEN-LAST:event_txtSearchFocusGained

        private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MousePressed
                // TODO add your handling code here:
                ThemCauHoi tch = new ThemCauHoi((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
                tch.setVisible(true);

        }// GEN-LAST:event_jLabel2MousePressed

        private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MousePressed
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow >= 0) {
                        int questionId = (Integer) jTable1.getModel().getValueAt(selectedRow, 0);
                        SuaCauHoi suaCauHoiDlg = new SuaCauHoi(new javax.swing.JFrame(), true, questionId);
                        suaCauHoiDlg.setVisible(true);
                } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn câu hỏi cần sửa!");
                }
        }// GEN-LAST:event_jLabel1MousePressed

        private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MousePressed
                // Handle delete question
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow >= 0) {
                        int questionId = (Integer) jTable1.getModel().getValueAt(selectedRow, 0);

                        // Show confirmation dialog
                        int option = JOptionPane.showConfirmDialog(
                                        this,
                                        "Bạn có chắc chắn muốn xóa câu hỏi này không?",
                                        "Xác nhận xóa",
                                        JOptionPane.YES_NO_OPTION);

                        if (option == JOptionPane.YES_OPTION) {
                                // Soft delete the question by setting status to 0
                                BUS_Questions busQuestions = new BUS_Questions();
                                int result = busQuestions.softDelete(questionId);

                                if (result > 0) {
                                        JOptionPane.showMessageDialog(this, "Xóa câu hỏi thành công!");
                                        // Reload the questions table to reflect the changes
                                        loadQuestionsTable();
                                } else {
                                        JOptionPane.showMessageDialog(this, "Xóa câu hỏi thất bại. Vui lòng thử lại.",
                                                        "Lỗi", JOptionPane.ERROR_MESSAGE);
                                }
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "Vui lòng chọn một câu hỏi để xóa!",
                                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
        }// GEN-LAST:event_jLabel4MousePressed

        private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSearchActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtSearchActionPerformed

        // Add a helper method to get topic name from ID
        private String getTopicName(int topicId) {
                if (topics != null) {
                        for (DTO.DTO_Topic topic : topics) {
                                if (topic.getTpID() == topicId) {
                                        return topic.getTpTitle();
                                }
                        }
                }
                return "Không xác định";
        }

        public void loadQuestionsTable() {
                BUS.BUS_Questions busQuestions = new BUS_Questions();
                java.util.ArrayList<DTO.DTO_Questions> questions = busQuestions.getAllData();
                String[] columns = { "ID", "Nội dung", "Chủ đề", "Độ khó" };
                javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columns, 0) {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                                return false;
                        }
                };
                int stt = 1;
                for (DTO.DTO_Questions q : questions) {
                        // Look up topic name instead of using the topic ID directly
                        String topicName = getTopicName(q.getqTopicID());

                        Object[] rowData = new Object[] {
                                        q.getqID(),
                                        q.getqContent(),
                                        topicName, // Use topic name instead of ID
                                        q.getqLevel()
                        };
                        model.addRow(rowData);
                        stt++;
                }
                jTable1.setModel(model);

                javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }
        }

        /**
         * Search for questions based on the given keyword
         * 
         * @param keyword The search keyword
         */
        private void searchQuestions(String keyword) {
                try {
                        BUS_Questions busQuestions = new BUS_Questions();
                        ArrayList<DTO.DTO_Questions> questions = busQuestions.searchQuestions(keyword);

                        if (questions.isEmpty()) {
                                lblSearch.setText("Không tìm thấy câu hỏi phù hợp.");
                                lblSearch.setForeground(Color.RED);

                                // Clear the table
                                String[] columns = { "ID", "Nội dung", "Chủ đề", "Độ khó" };
                                DefaultTableModel model = new DefaultTableModel(columns, 0) {
                                        @Override
                                        public boolean isCellEditable(int row, int column) {
                                                return false;
                                        }
                                };
                                jTable1.setModel(model);
                        } else {
                                // Update the table with search results
                                String[] columns = { "ID", "Nội dung", "Chủ đề", "Độ khó" };
                                DefaultTableModel model = new DefaultTableModel(columns, 0) {
                                        @Override
                                        public boolean isCellEditable(int row, int column) {
                                                return false;
                                        }
                                };

                                for (DTO_Questions q : questions) {
                                        // Look up topic name
                                        String topicName = getTopicName(q.getqTopicID());

                                        Object[] rowData = new Object[] {
                                                        q.getqID(),
                                                        q.getqContent(),
                                                        topicName, // Use topic name instead of ID
                                                        q.getqLevel()
                                        };
                                        model.addRow(rowData);
                                }

                                jTable1.setModel(model);

                                // Format the table columns
                                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                                centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                                        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                                }

                                lblSearch.setText("Tìm thấy " + questions.size() + " kết quả.");
                                lblSearch.setForeground(new Color(0, 102, 0)); // Dark green
                        }
                } catch (Exception e) {
                        e.printStackTrace();
                        lblSearch.setText("Lỗi tìm kiếm: " + e.getMessage());
                        lblSearch.setForeground(Color.RED);
                }
        }

        // Add this method to your class to load topics into the combo box
        private void loadTopics() {
                try {
                        BUS.BUS_Topics topicsBUS = new BUS.BUS_Topics();
                        topics = topicsBUS.getAllTopics();

                        // First item is "All topics"
                        cboTopic.removeAllItems();
                        cboTopic.addItem("Tất cả chủ đề");

                        // Add topics to combo box
                        if (topics != null && !topics.isEmpty()) {
                                for (DTO.DTO_Topic topic : topics) {
                                        cboTopic.addItem(topic.getTpTitle());
                                }
                        }
                } catch (Exception e) {
                        e.printStackTrace();
                }
        }

        // New method to handle filtering based on all criteria
        private void filterQuestions() {
                String keyword = txtSearch.getText().trim();
                int topicIndex = cboTopic.getSelectedIndex();
                String difficulty = cboDifficulty.getSelectedItem().toString();

                // Get the topic ID (-1 means all topics)
                int topicId = -1;
                if (topicIndex > 0) { // If not "All topics"
                        topicId = topics.get(topicIndex - 1).getTpID();
                }

                // If difficulty is "All", set to empty
                if (difficulty.equals("Tất cả")) {
                        difficulty = "";
                }

                // If all filters are default, load all questions
                if (keyword.isEmpty() && topicId == -1 && difficulty.isEmpty()) {
                        loadQuestionsTable();
                        lblSearch.setText("");
                } else {
                        searchQuestions(keyword, topicId, difficulty);
                }
        }

        // Update the searchQuestions method to include the new filters
        private void searchQuestions(String keyword, int topicId, String difficulty) {
                try {
                        BUS_Questions busQuestions = new BUS_Questions();
                        ArrayList<DTO.DTO_Questions> questions = busQuestions.searchQuestionsFiltered(keyword, topicId, difficulty);

                        if (questions.isEmpty()) {
                                lblSearch.setText("Không tìm thấy câu hỏi phù hợp.");
                                lblSearch.setForeground(Color.RED);

                                // Clear the table
                                String[] columns = { "ID", "Nội dung", "Chủ đề", "Độ khó" };
                                DefaultTableModel model = new DefaultTableModel(columns, 0) {
                                        @Override
                                        public boolean isCellEditable(int row, int column) {
                                                return false;
                                        }
                                };
                                jTable1.setModel(model);
                        } else {
                                // Update the table with search results
                                String[] columns = { "ID", "Nội dung", "Chủ đề", "Độ khó" };
                                DefaultTableModel model = new DefaultTableModel(columns, 0) {
                                        @Override
                                        public boolean isCellEditable(int row, int column) {
                                                return false;
                                        }
                                };

                                for (DTO_Questions q : questions) {
                                        // Look up topic name
                                        String topicName = getTopicName(q.getqTopicID());

                                        Object[] rowData = new Object[] {
                                                        q.getqID(),
                                                        q.getqContent(),
                                                        topicName, 
                                                        q.getqLevel()
                                        };
                                        model.addRow(rowData);
                                }

                                jTable1.setModel(model);

                                // Format the table columns
                                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                                centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                                        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                                }

                                lblSearch.setText("Tìm thấy " + questions.size() + " kết quả.");
                                lblSearch.setForeground(new Color(0, 102, 0)); // Dark green
                        }
                } catch (Exception e) {
                        e.printStackTrace();
                        lblSearch.setText("Lỗi tìm kiếm: " + e.getMessage());
                        lblSearch.setForeground(Color.RED);
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel lblSearch;
        private com.raven.suportSwing.MyButton myButton2;
        private com.raven.suportSwing.ScrollBarCustom scrollBarCustom1;
        private com.raven.suportSwing.TextField txtSearch;
        // End of variables declaration//GEN-END:variables
}
