/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.CRUD;

import java.lang.reflect.Array;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import BUS.BUS_Exam;
import BUS.BUS_Questions;
import BUS.BUS_Test;
import DTO.DTO_Exam;
import DTO.DTO_Questions;
import DTO.DTO_Test;

/**
 *
 * @author KIET
 */
public class ThemDeThi extends javax.swing.JDialog {
    BUS_Test testBUS = new BUS_Test();
    ArrayList<DTO_Test> listTest = new ArrayList<>();
    BUS_Questions questionBUS = new BUS_Questions();
    ArrayList<DTO_Questions> listQuestion = new ArrayList<>();
    BUS_Exam examBUS = new BUS_Exam();
    ArrayList<DTO_Exam> listExam = new ArrayList<>();

    /** Creates new form ThemDeThi */
    public ThemDeThi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // căn giữa màn hình
        this.setLocationRelativeTo(null);
        // load data vào combobox
        jComboBox1.removeAllItems();
        listTest = testBUS.getAllData();
        for (DTO_Test test : listTest) {
            jComboBox1.addItem(test.getTestCode());
        }
        listQuestion = questionBUS.getAllData();
        listExam = examBUS.getAllData();

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("TẠO ĐỀ THI");

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Chọn code Bài Thi");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText(" ");

        jLabel5.setText(" ");

        jButton1.setText("XÁC NHẬN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nhập số lượng:");

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                320,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBox1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                313,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(73, 73, 73)
                                                                                .addComponent(jLabel7)))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 309,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 61, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // nếu số lượng <=0 và >10 thì thông bao
        if (Integer.parseInt(jTextField1.getText()) <= 0 || Integer.parseInt(jTextField1.getText()) > 10) {
            JOptionPane.showMessageDialog(null, "Số lượng câu hỏi lơn hơn 0 và nhỏ hơn bằng 10");
            return;
        }
        String testCode = jComboBox1.getSelectedItem().toString();
        int soLuongDeThi = Integer.parseInt(jTextField1.getText());
        boolean check = true;
        int soluongdethicoma = 0;
        for (DTO_Exam exam : listExam) {
            if (exam.getTestCode().equals(testCode)) {
                soluongdethicoma++;
            }
        }
        if (soluongdethicoma >= 10) {
            JOptionPane.showMessageDialog(null, "Số lượng đề thi đã đạt tối đa");
            return;
        }
        if (soLuongDeThi + soluongdethicoma > 10) {
            JOptionPane.showMessageDialog(null, "Bạn chỉ có thể tạo thêm + " + (10 - soluongdethicoma) + " đề thi");
            return;
        }

        DTO_Test test = new DTO_Test();
        for (DTO_Test t : listTest) {
            if (t.getTestCode().equals(testCode)) {
                test = t;
                break;
            }
        }
        int soLuongCauHoiDe = test.getNumEasy();
        int soLuongCauHoiTrungBinh = test.getNumMedium();
        int soLuongCauHoiKho = test.getNumDiff();
        System.out.println("listQuestion: " + listQuestion.size());
        // lay tat ca cau hoi co ma chu de
        ArrayList<DTO_Questions> listQuestionByTopic = new ArrayList<>();
        System.out.println("Mã chủ đề có  dc:" + test.getTpID());
        for (DTO_Questions question : listQuestion) {
            if (question.getqTopicID() == test.getTpID()) {
                listQuestionByTopic.add(question);
            }
        }
        System.out.println("listQuestionByTopic: " + listQuestionByTopic.size());
        for (DTO_Questions question : listQuestionByTopic) {
            System.out.println(question);
        }
        int maxExOrderByTestCode = 0;
        for (DTO_Exam exam : listExam) {
            System.out.println(exam);
            if (exam.getTestCode().equals(testCode)) {
                int exOrder = Integer.parseInt(exam.getExOrder());
                if (exOrder > maxExOrderByTestCode) {
                    maxExOrderByTestCode = exOrder;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "maxExOrderByTestCode: " + maxExOrderByTestCode);
        while (soLuongDeThi > 0) {
            int cntDe = 0;
            int cntTrungBinh = 0;
            int cntKho = 0;
            ArrayList<DTO_Questions> listQuestionMucDo = new ArrayList<>();
            for (DTO_Questions question : listQuestionByTopic) {
                if (question.getqLevel().equals("Dễ") && cntDe <= soLuongCauHoiDe) {
                    cntDe++;
                    listQuestionMucDo.add(question);
                } else if (question.getqLevel().equals("Vừa") && cntTrungBinh <= soLuongCauHoiTrungBinh) {
                    cntTrungBinh++;
                    listQuestionMucDo.add(question);
                } else if (question.getqLevel().equals("Khó") && cntKho <= soLuongCauHoiKho) {
                    cntKho++;
                    listQuestionMucDo.add(question);
                }
                if (cntDe == soLuongCauHoiDe && cntTrungBinh == soLuongCauHoiTrungBinh && cntKho == soLuongCauHoiKho) {
                    break;
                }
            }
            System.out.println("listQuestionMucDo: " + listQuestionMucDo.size());

            String listQuestionCode = "";
            for (DTO_Questions question : listQuestionMucDo) {
                listQuestionCode += question.getqID() + ",";
            }
            if (listQuestionCode.length() > 0) {
                listQuestionCode = listQuestionCode.substring(0, listQuestionCode.length() - 1);
            }

            System.out.println(listQuestionCode);
            // tạo đề thi
            DTO_Exam exam = new DTO_Exam();
            exam.setTestCode(testCode);
            maxExOrderByTestCode++;
            String maxExOrder = String.valueOf(maxExOrderByTestCode);
            exam.setExOrder(maxExOrder);
            exam.setExCode(testCode + "_" + maxExOrder);
            exam.setEx_quesIDs(listQuestionCode);
            int result = examBUS.insert(exam);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Tạo đề thi thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Tạo đề thi thất bại");
            }
            soLuongDeThi--;
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemDeThi dialog = new ThemDeThi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
